import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import Header from '@/app/header/page';
import Footer from '@/app/footer/page';

export const metadata: Metadata = {
  title: 'Marvel Characters',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
    children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
